### ISSUE TITLE
Example of the place to set the ApiKey

### ISSUE THREAD

**Issue by manuelmejiaio** [RoushTech/SparkPostDotNet#5]
Show an example to place the ApiKey ...could be in a json file. Right know the examples doesn't show where to place the ApiKey.

**Comment by StrangeWill** [comment]
Currently under SparkPost.ApiKey in your JSON config.

SparkPostDotNet needs some love, maybe I'll give it some this week. I ended up not needing it so it's kind of sat stale, but if there is interest I'll totally get it up to spec.

**Comment by StrangeWill** [comment]
@mejiamanuel57 Check out the new updated readme and pull 0.2.0 from Nuget, let me know if that works for you.

We are missing a ton of API functionality, so let me know if you need more.
